entrypoint: /python/bin/fdk /function/func.py handler
memory: 1024
name: predictor
runtime: python3.6
schema_version: 20180708
triggers:
- name: predictor
  source: /predictor
  type: http
version: 0.0.1
